name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 8
          cache: gradle

      - name: Validation Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5

      - name: Build with Gradle
        id: build_with_gradle
        run: ./gradlew build

      - name: Delete old CI release
        id: delete_old_ci_release
        if: steps.build_with_gradle.outcome == 'success' && contains(github.ref, github.event.repository.default_branch)
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tag_pattern: ci_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new CI release
        if: steps.delete_old_ci_release.outcome == 'success' && contains(github.ref, github.event.repository.default_branch)
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: CI release
          tag_name: ci_release
          body: ${{ format('From [`{0}`]({1}) ({2})', github.event.head_commit.message, github.event.head_commit.url, github.sha) }}
          files: ./build/libs/*
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}